# NumPy

In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### 1D array

In [2]:
a=np.array([10,20,30,40,50,60])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(6,)

In [5]:
a.ndim

1

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[2]

30

In [9]:
a[-2]

50

#### Multi dimensional array

In [10]:
b=np.array([[10,20,30],[40,50,60]])

### attributes of arrays

In [11]:
b.shape

(2, 3)

In [12]:
b.dtype

dtype('int32')

In [13]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
b.size

6

In [16]:
b.ndim

2

#### indexing

In [17]:
b[0]

array([10, 20, 30])

In [18]:
b[1]

array([40, 50, 60])

In [20]:
b[-1]

array([40, 50, 60])

#### another type of multi dimensional arrays

In [33]:
c=np.array([[[1,2,3,4],[5,6,7]]])

In [34]:
c

array([[list([1, 2, 3, 4]), list([5, 6, 7])]], dtype=object)

In [35]:
c.shape

(1, 2)

In [25]:
c.size

4

In [26]:
c.ndim

3

In [27]:
c.dtype

dtype('int32')

#### first element in first array

In [28]:
b[0][0]

10

In [31]:
b[1][0]

40

In [39]:
c[0][0]

[1, 2, 3, 4]

#### second element in second array

In [41]:
b[1][1]

50

#### change datatype into float

In [42]:
b=np.array([[10,20,30,],[23,55,15]],dtype=float)

In [45]:
a=np.array([[[[1,2,3,4,5,6]]]])

In [46]:
a[0,0,0,3]

4

In [48]:
b

array([[10., 20., 30.],
       [23., 55., 15.]])

#### create a bigger array

In [8]:
a1=np.array([
    [
    [10,20,30,40],[8,8,2,1],[1,1,1,2]
    ],
    [
    [9,9,2,39],[1,2,3,4],[5,6,7,8]
    ],
    [
    [11,22,33,44],[55,66,77,88],[99,52,45,78]    
    ]
    ],dtype=float)   
    


In [9]:
a1.shape

(3, 3, 4)

In [10]:
a1.ndim

3

In [11]:
a1.size

36

In [13]:
a1[2][2][3]

78.0

In [14]:
a1[2][2]

array([99., 52., 45., 78.])

In [15]:
a1[1][1][2]

3.0

#### filling arrays

In [24]:
a_full=np.full((5,5,4),7)

In [25]:
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [18]:
b_full=np.full((2,4,3),8)

In [19]:
b_full

array([[[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]])

In [27]:
a_full.ndim

3

In [21]:
b_full.ndim

3

### zeros and ones

In [28]:
a_zeros=np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
b2=np.ones((2,3,4))
b2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
b2.ndim

3

### empty and random

In [31]:
e=np.empty((4,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [32]:
a_random=np.random.random((2,2))
a_random

array([[0.88068865, 0.50421687],
       [0.88674881, 0.03701331]])

In [33]:
a_random.ndim

2

In [34]:
a_random.size

4

### ranges

### Arange

In [35]:
arange=np.arange(10,50,5)

In [36]:
arange

array([10, 15, 20, 25, 30, 35, 40, 45])

### linspace

#### start-stop number of values

In [39]:
linspace=np.linspace(0,50,2)
linspace

array([ 0., 50.])

In [41]:
linspace.ndim

1

In [42]:
linspace.size

2

In [43]:
linspace1=np.linspace(0,50,30)

In [44]:
linspace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [45]:
linspace1.size

30

In [46]:
linspace2=np.linspace(0,50,25,dtype=int)
linspace2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

### math functions

In [47]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [48]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26, 2.51543867e+30, 5.54062238e+34,
       1.22040329e+39, 2.68811714e+43])

In [49]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062,  0.77389068, -0.99388865,  0.89399666, -0.50636564])

In [50]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298,  0.6333192 , -0.11038724, -0.44807362,  0.86231887])

In [51]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061,
        0.32004039,  1.22195992,  9.00365495, -1.99520041, -0.58721392])

In [52]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456, 4.24849524, 4.38202663, 4.49980967, 4.60517019])

In [53]:
np.sqrt(a)

array([ 3.16227766,  4.47213595,  5.47722558,  6.32455532,  7.07106781,
        7.74596669,  8.36660027,  8.94427191,  9.48683298, 10.        ])

#### aggregate functions

In [54]:
a.sum()

550

In [55]:
a.min()

10

In [56]:
a.max()

100

In [57]:
a.mean()

55.0

In [58]:
np.median(a)

55.0

In [59]:
np.std(a)

28.722813232690143

#### create some arrays and apply all the functions

In [61]:
np.median(linspace2)

25.0

In [62]:
np.sum(linspace2)

614

In [63]:
np.sqrt(linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [64]:
np.std(linspace2)

14.924020905908701

In [65]:
np.cos(linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])